name: Black Duck Security Scan

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

jobs:
  black_duck:
    name: Run Black Duck security scaner
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3

    - name: Synopsys Detect
      uses: synopsys-sig/detect-action@v0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        detect-version: 7.9.0
